### ISSUE TITLE
Text hard to read (#9)

### ISSUE THREAD

**Issue by TheTerrorByte** [dean1012/memes-with-friends#18] opened 2017-06-05 17:47 UTC
Sorry i wasnt able to respond to the other issue, but it still persists.
![mwf8](https://cloud.githubusercontent.com/assets/8520072/26795918/483762e6-49dc-11e7-979b-55a299ccffb8.png)
res 1366x768

**Comment by dean1012** [comment] 2017-06-05 19:01
Pulling in @EliteTK 

Once @EliteTK has pulled in a better scaling system, this should resolve. I'll keep it open for tracking purposes.

**Comment by EliteTK** [comment] 2017-06-05 21:41
I'm looking at making things scale nicely now.

**Comment by EliteTK** [comment] 2017-06-05 22:37
Ok, I'll create an issue detailing my plan for solving this in the coming week. I have a few ideas which might be worth considering or even mixing. One idea is something I recently used at work which served me well in terms of satisfying the specification I had written up.

**Comment by dean1012** [comment] 2017-06-21 18:52
@EliteTK any update on this? i haven't seen a new issue regarding better rendering yet

**Comment by EliteTK** [comment] 2017-06-22 12:21
@dean1012 I've been working on a project of my own (using SDL2) to get a good grasp of how C++ works best when dealing with a C library and I think the first step would be to wrap the aspects of allegro that we do use in some classes in such a way that we do not need to use unique_ptr and shared_ptr everywhere with custom deleters.

This will make things a bit cleaner to work with, function names will be generally shorter and we can specialize some things to work in the way we want them to work. This thick binding around allegro 5 will clean up a lot of code.

I am also going to put together a short write-up of some design aspects of memes-with-friends which could be improved upon (some of these design aspects would be best solved after this wrapper is completed rather than before). This should include some basic proposals for how to deal with the rendering at different resolutions problem, including an overhaul of GameDisplay (I think this could be renamed to "Display", the "Game" bit is entirely superfluous but that's beside the point).

**Comment by EliteTK** [comment] 2017-06-23 12:24
@dean1012 I've started work on this allegro5 wrapper with good progress and success, it should be finished pretty quickly and the simplifications to the source will be immediately visible.

**Comment by dean1012** [comment] 2017-06-23 16:43
@EliteTK Cool can't wait to see it. @TheTerrorByte will benefit too.

**Comment by TheTerrorByte** [comment] 2017-07-04 02:10
Still an issue in the latest version.

**Comment by dean1012** [comment] 2017-07-04 04:47
It's not a perfect fix but when my menu PR is merged, this issue should be alleviated. See the testing build to confirm: https://www.dropbox.com/s/4yrof4zeywzsu9p/Testers.zip?dl=0

This will work now until @EliteTK or @TheTerrorByte comes up with a better solution.

**Comment by TheTerrorByte** [comment] 2017-07-04 04:54
I think you should make the game itself scale with resolution, not just the window, since after opening debug info I noticed that it reports the mouse location as if the game window is 1920x1080. The problem seems to be the game thinking it's 1920x1080 despite the actual screen size being different, so instead of changing just the screen size, maybe make it so the game itself runs in the native screen resolution. This could be why the text is buggy.

Or perhaps adding resolution options and windowed mode.

**Comment by dean1012** [comment] 2017-07-04 04:59
Right now the game is 1920x1080. Everything is drawn to the screen in that resolution and mouse movements are also handled in that resolution. The actual screen coordinates are converted to that screen space which is why the debug info reports in 1920x1080 regardless of your resolution.

The screen itself is then scaled up or (in your case) down to fit your screen resolution.

As a cheap fix to the text issue, I am increasing the font size to 20 when scaling down from 1920x1080. Native resolution and above (scaling up) will continue to use font size 12.

Is the text more readable now? I changed my desktop resolution to 1366x768 and I could read the text just fine.

As far as I'm concerned, the issue is fixed as long as the text is readable. There's other more important functionality to be put in place.

If this were a commercial product, I'd agree with you that this isn't appropriate. However, it's a summer project with the goal of getting something done so some things are acceptable when they wouldn't otherwise be.

With that said, @EliteTK is the one actually working on this fix. It's very possible he will release a patch soon(ish) that actually resolves the issue. Until then, I'm satisfied as long as the text is readable for you.

**Comment by dean1012** [comment] 2017-07-05 02:51
I am closing this issue as it appears to be fixed to an acceptable degree and no further solution is on the horizon at this time.

**Closed by dean1012** 2017-07-05 02:51 UTC
Labels: bug
